# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fpRw6yeecbmLifcOObOKz_QEK_O64yDe
"""

import pandas as pd

df = pd.read_csv('/content/seoul_temp.csv')
df

"""역슬래시 t 지우기"""

df['년']= df['년'].str[3:]

df

"""isnull, sum"""

df.isnull()

df.isnull().sum()

"""dropna"""

df.dropna(subset=['지점'],inplace=True)
df.isnull().sum()

"""fillna"""

df.fillna(df.mean(),inplace=True)
df.isnull().sum()

df

"""1988년 이후 데이터 조회"""

df[df['년']>'1988']

"""1988년 이후 데이터 중 평균 기온 13도 이상인 데이터 구하기"""

df[df['평균기온'] > 13 ]

"""컬럼이름 연 년도"""

df.rename(columns={'년':'연도'},inplace=True)
df

"""nlargest    nsmallest"""

df.nlargest(5,'평균기온')

df.nsmallest(5,'평균기온')

"""평균 13도 이상 그리고 최저 9.3 미만"""

df[(df['평균기온']>= 13) & (df['최저기온']<9.3)]

df['연도']= df['연도'].astype(int)
df[(df['평균기온'] > 15) & (df['최고기온'] >= 16.5) & (df['연도'] >= 1990) & (df['연도'] <= 2010)]

"""평균기온 가장 높 가장 낮 최고기온 가장 높 낮"""

df.nlargest(1,'평균기온')

df.nsmallest(1,'평균기온')

df.nlargest(1,'최고기온')

df.nsmallest(1,'최고기온')

df[df['연도']==1977]

df[df['연도']==1978]

"""연도에 따른 평균 기온 변화"""

import matplotlib.pyplot as plt
x = df['연도']
y = df['평균기온']
x_max = df['최고기온']
y_max = df['최저기온']
plt.plot(x,y,color='green',label='p')
plt.plot(x,x_max,color='red',label='h')
plt.plot(x,y_max,color='blue',label='l')
plt.title('seoul temp')
plt.xlabel('year')
plt.ylabel('temp')
plt.grid()
plt.legend()
plt.show()